Update komanda script with install

diff --git a/scripts/komanda b/scripts/komanda
--- a/scripts/komanda
+++ b/scripts/komanda
@@ -2,10 +2,22 @@
 
 # Install and/or invoke Komanda
 
-if ! test -e komanda-cli
+if ! which komanda-cli >/dev/null 2>&1
 then
-  echo 2>&1 "Komanda not installed: check https://github.com/mephux/komanda-cli"
-  exit 1
+  echo "Installing Komanda"
+  go get github.com/mephux/komanda-cli \
+    && go install github.com/mephux/komanda-cli \
+    || {
+    echo 2>&1 "Error installing komanda-cli"
+    exit 1
+  }
 fi
 
-exec komanda-cli -c $HOME/secrets/komanda.cfg
+CFG="$HOME/secrets/komanda.cfg"
+WORKCFG="$HOME/work.komanda.cfg"
+if test -f "$WORKCFG"
+then
+  CFG="$WORKCFG"
+fi
+
+exec komanda-cli -c $CFG
